Change column type of zendesk_ticket.external_id to text
The "external_id" reponse from Zendesk API may be a string, for example
if an extnernal ID is a side conversation in to slack, causing a
failure:

steampipe=> select created_at, description, id, status, subject from zendesk_ticket where organization_id ='361091712552' ;
ERROR:  rpc error: code = Unknown desc = interfaceToColumnValue failed for column 'external_id': strconv.ParseInt: parsing "zen:side_conversation:7f21fa9b-ae2f-11ed-b2ad-ec87d0fe7ae2:ticket:1234": invalid syntax

Changing this column type to text resolves this error